### ISSUE TITLE
[Android] App crashes when trying to scan

### ISSUE THREAD

**Issue by BokiGaja** [Anyline/anyline-ocr-react-native-module#100]
Hi,
I am trying to implement your package to React Native project and there is a problem with the Android integration.

**Anyline React-Native Plugin version: v27.1.0**  
**react-native: v0.63.4**

**I'm submitting a ...**  
[x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x ] Android
[ ] iOS

**Current behavior:**
App crashes both on Android simulator and on a real device simulator once **AnylineOCR.setup** function is triggered

**Expected behavior:**
Open Anyline scan screen as it does on the IOS simulator

**Note:**
**getPackages()** function in **MainApplication.java** is looking a bit different than the one in your integration tutorial and the packages are auto-linked:

`@Override
        protected List<ReactPackage> getPackages() {
          List<ReactPackage> packages = new PackageList(this).getPackages();
          return packages;
  }
`

**Comment by scamp81** [comment]
I'm running into this issue as well, any updates?

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
