### ISSUE TITLE
plugin paid or not?

### ISSUE THREAD

**Issue by shivarajRBG** [Anyline/anyline-ocr-react-native-module#101]
Hi,
I want to use this plugin for my vehicle plate number recognition but before proceeding further please let me know for license do we need to pay or its is free?

**Comment by renatoAnyline** [comment]
hi ShivarajRBG,

we do have a trial license but for use in production it is necessary to use a regular paid license.

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
