### ISSUE TITLE
Does it support arabic vehicle number plates reading? 

### ISSUE THREAD

**Issue by shivaraj12345** [Anyline/anyline-ocr-react-native-module#102]
**Anyline React-Native Plugin version:** 

**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[ ] iOS

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert code snippets here
```

**Other information:**

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
