### ISSUE TITLE
iOS Barcode scan - UNKNOWN type for valid barcode

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#12]
Sorry to hit you with so many issues at once :)

I'm reading this barcode and getting type "UNKNOWN": https://dmv.ny.gov/sites/default/files/styles/panopoly_image_original/public/edl_lp_back_hilights_text_2.png?itok=zwLP3KxT

this online barcode reader doesn't have trouble with it: https://online-barcode-reader.inliteresearch.com/

I also tried this one, with the same result: https://cadmv.files.wordpress.com/2010/12/dl-back.jpg
and then I tried my own driver license...with the same result

hope this gets resolved soon, thanks!

**Comment by JonasLaux** [comment]
#10
