### ISSUE TITLE
Duplicate Class issues if add anyline module

### ISSUE THREAD

**Issue by aim8526** [Anyline/anyline-ocr-react-native-module#120]
**Anyline React-Native Plugin version:** 

34.0.0

**I'm submitting a ...**  
[*] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[*] Android
[ ] iOS

**Current behavior:**

facing a lot of duplicate class issues after adding anyline-ocr-react-native-module....

Duplicate class org.spongycastle.util.test.SimpleTest found in modules anylinesdk-34.0.0-runtime.jar (io.anyline:anylinesdk:34.0.0) and core-1.58.0.0.jar (com.madgag.spongycastle:core:1.58.0.0)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert code snippets here
```

**Other information:**

**Comment by ricardocolombo** [comment]
Hi,

No. As of now, if you have this encounter this issue with `com.madgag.spongycastle` libraries, please downgrade to Anyline v32. 
We will work on a fix for it, but still cannot provide an ETA. 

Sorry for the inconvenience.

**Comment by ricardocolombo** [comment]
Could you let us know which version of React Native you are using?

Thanks!

**Comment by aim8526** [comment]
> Could you let us know which version of React Native you are using?
> 
> Thanks!

Currently using  "react-native": "^0.64.0" 
for my app.

I had already tried version 31, 32, 33. 

32 and 33 had the same `com.madgag.spongycastle`  and other core classes conflict.
Where as v31 having issues if i have react-native camera, that's why I removed react-native camera, after that v31 is working in my case.
