### ISSUE TITLE
NPM update for latest version 35.0

### ISSUE THREAD

**Issue by hsandhu** [Anyline/anyline-ocr-react-native-module#129]
Looks like there is a delay between the latest version being pushed to npm?

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
