### ISSUE TITLE
Install via npm

### ISSUE THREAD

**Issue by lgrayland** [Anyline/anyline-ocr-react-native-module#13]
there seems to be a problem when trying to install the package via npm, where it is getting stuck at: loadRequestedDeps: sill install loadAllDepsIntoIdealTree

**Comment by JonasLaux** [comment]
Hi, 
this seems to be an issue with your permissions, not with the package itself, check [here](https://github.com/npm/npm/issues/11482#issuecomment-224897574).
If you still have problems installing via npm, please try
`npm install -verbose`
and let me know the output.

**Comment by lgrayland** [comment]
Here's the output using verbose, tried the same command with sudo and gets to the same point and hangs

➜  TestApp  npm i anyline-ocr-react-native-module --save --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node4-lts/4.5.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   'anyline-ocr-react-native-module',
npm verb cli   '--save',
npm verb cli   '--verbose' ]
npm info using npm@3.10.9
npm info using node@v6.5.0
npm verb request uri https://registry.npmjs.org/anyline-ocr-react-native-module
npm verb request no auth needed
npm info attempt registry request try #1 at 3:03:37 PM
npm verb request id 0d7e203f13e3876e
npm verb etag W/"587f9e89-1bca"
npm verb lastModified Wed, 18 Jan 2017 16:57:45 GMT
npm http request GET https://registry.npmjs.org/anyline-ocr-react-native-module
npm http 304 https://registry.npmjs.org/anyline-ocr-react-native-module
npm verb headers { date: 'Wed, 25 Jan 2017 14:03:37 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"587f9e89-1bca"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-mad9423-MAD',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1485353017.651128,VS0,VE50',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/anyline-ocr-react-native-module from cache
npm verb get saving anyline-ocr-react-native-module to /Users/lukegrayland/.npm/registry.npmjs.org/anyline-ocr-react-native-module/.cache.json
npm verb correctMkdir /Users/lukegrayland/.npm correctMkdir not in flight; initializing
npm verb cache add spec anyline-ocr-react-native-module
npm verb addNamed "latest" is being treated as a dist-tag for anyline-ocr-react-native-module
npm info addNameTag [ 'anyline-ocr-react-native-module', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/anyline-ocr-react-native-module not in flight; fetching
npm verb get https://registry.npmjs.org/anyline-ocr-react-native-module not expired, no request
npm verb addNamed "3.8.1" is a plain semver version for anyline-ocr-react-native-module
npm verb addRemoteTarball https://registry.npmjs.org/anyline-ocr-react-native-module/-/anyline-ocr-react-native-module-3.8.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/anyline-ocr-react-native-module/-/anyline-ocr-react-native-module-3.8.1.tgz',
npm verb addRemoteTarball   '35bf3ed5014eddd91138b6531b4d0c62284e4207' ]
npm info retry fetch attempt 1 at 3:03:38 PM
npm info attempt registry request try #1 at 3:03:38 PM
npm http fetch GET https://registry.npmjs.org/anyline-ocr-react-native-module/-/anyline-ocr-react-native-module-3.8.1.tgz
npm http fetch 200 https://registry.npmjs.org/anyline-ocr-react-native-module/-/anyline-ocr-react-native-module-3.8.1.tgz
[    ..............] | loadRequestedDeps: http fetch 200 https://registry.npmjs.org/anyline-ocr-react-native-module/-/anyline-ocr-react-native-module-3.8.1.tgz

**Comment by JonasLaux** [comment]
Okay, thanks for sharing.
I now see that i pushed the whole example folder on npm, which could cause long loading times. I pushed it again (slim version now 😃). Shouldn't stuck again this point. 
Thank you for mentioning!

**Comment by lgrayland** [comment]
perfect , thanks for fixing
