### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by lgrayland** [Anyline/anyline-ocr-react-native-module#14]
I am seeing an app crash message (see below) after scanning a meter

![image](https://cloud.githubusercontent.com/assets/8897696/22558343/9eca33a6-e96d-11e6-8ac3-930c7a69ae68.png)

I have tried running the example app to test, so everything in the code is the same as that. I'm not seeing anything in the console logs indicating any kind of error just the console logs that are already in the example code.

The current device im running the app on is running a slightly older version of android, 4.2.2, the setting in the build gradle are:

compileSdkVersion 25
buildToolsVersion '25.0.1'
defaultConfig {
    applicationId "com.appID"
    minSdkVersion 17
    targetSdkVersion 25
    versionCode 1
    versionName "1.0"
    ndk {
        abiFilters "armeabi-v7a", "x86"
    }
}

Currently, this is the only device I have for testing and assume the module won't run on an emulator

**Comment by JonasLaux** [comment]
Hi, 
thanks for mentioning. This is kind of difficult without any hint or log. 
Did you get the log with android studio device monitor (to get all logs of the bundle)?
Are you sure, that no runtime exception is thrown because of the license?
Did you get an developer license for your applicationID?
Let me know if you find any hints that could cause the error.

**Comment by lgrayland** [comment]
[log.txt](https://github.com/Anyline/anyline-ocr-react-native-module/files/748588/log.txt)

have attached the error output from the device monitor, did see a fatal mentioning the missing permission for vibrate so will try adding that.

02-02 18:56:48.111: E/AndroidRuntime(30309): FATAL EXCEPTION: main
02-02 18:56:48.111: E/AndroidRuntime(30309): java.lang.RuntimeException: Vibrate on result enabled, but vibrate permission missing. Add permission <uses-permission android:name="android.permission.VIBRATE"/>

Can't see any error about the license, am using a trial one from the portal, is this the one for testing?

**Comment by JonasLaux** [comment]
Yes, when you have vibrateOnResult enabled in your config, you have to add the permissions to android. Just add the Vibrate Permission
`<uses-permission android:name="android.permission.VIBRATE"/>`
to your Manifest.
I hope this works for you.

**Comment by lgrayland** [comment]
tested this morning and the missing permission fixed the issue, thanks for the help. Might be good to add the needed permissions to the README. Also on the note of the README rnpm link is now included in react native so the command is react-native link

**Comment by JonasLaux** [comment]
You're right, the Readme should reflect that, thanks!
