### ISSUE TITLE
Scanner slow to open and close

### ISSUE THREAD

**Issue by gamble2020** [Anyline/anyline-ocr-react-native-module#142]
**Anyline React-Native Plugin version:** 

V39.0.0

**I'm submitting a ...**  
[x] bug report

**Occurring on ...**  
[ ] Android
[x] iOS

**Current behavior:**
MRZ scanner using ID plug-in slow to show  and hide

**Expected behavior:**
Should open and close without delay and janky performance 

**Steps to reproduce:**
Create new React Native app, add v39.0.0 plug-in via Podfile. Setup config for mrz with ID plug-in. Add basic button to open scanner.

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
