### ISSUE TITLE
Support react native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [Anyline/anyline-ocr-react-native-module#144]
**I'm submitting a ...**  
[ ] bug report
[x] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[x] iOS

See https://reactnative.dev/docs/next/new-architecture-library-intro

and https://reactnative.dev/docs/next/new-architecture-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by berndkamplanyline** [comment]
Hi @tom-sherman !

Thanks for submitting this feature request. As outlined below, please raise this feature request via our Helpdesk, that way we can keep track and inform you about the progress.

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
