### ISSUE TITLE
Failing first Android run

### ISSUE THREAD

**Issue by dhavrosh** [Anyline/anyline-ocr-react-native-module#16]
Hey guys,

I'm trying to use anyline-react-module in my project and it always fails. I installed module via npm and ran react-link. After that whenever i try to run-android i always get an error:

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find io.anyline:anylinesdk:3.12.0.
     Required by:
          What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find io.anyline:anylinesdk:3.12.0.
     Required by:
         MyProject:app:unspecified > MyProject:anyline-ocr-react-native-module:unspecified

Maybe someone knows how to solve it?

P.s. I tried an example and it works good, also i looked through gradle file and it seems to be ok

**Comment by JonasLaux** [comment]
Hi,

this may caused because your project may overwrite the repository of our gradle file.
Check out our Docu, [React-Native Advanced Topics](https://documentation.anyline.io/toc/platforms/react-native/advanced.html) for a detailed workaround.

**Comment by dhavrosh** [comment]
Thanks!
