### ISSUE TITLE
android build issue when trying to setup given example code

### ISSUE THREAD

**Issue by pramodpariharPK** [Anyline/anyline-ocr-react-native-module#167]
dowloaded code from https://github.com/Anyline/anyline-ocr-react-native-module this repo and followed the setups given to setup the react native project.
gradle sync succeeded but getting below error when trying to run the android project in android studio,
<img width="1457" alt="Screenshot 2023-06-21 at 5 37 33 PM" src="https://github.com/Anyline/anyline-ocr-react-native-module/assets/12712340/186bf300-b7a2-44c4-83b4-32f33de99051">

<img width="1457" alt="Screenshot 2023-06-21 at 5 37 45 PM" src="https://github.com/Anyline/anyline-ocr-react-native-module/assets/12712340/c59f3e57-3515-4f85-826e-eb263ad78e84">

<img width="1457" alt="Screenshot 2023-06-21 at 5 37 54 PM" src="https://github.com/Anyline/anyline-ocr-react-native-module/assets/12712340/c76b2da2-2971-481d-bf51-0275e966d1cb">

**Comment by berndkamplanyline** [comment]
Hi @pramodpariharPK!

Please make sure you're using a supported version of the JDK, such as JDK-11. That said, we don't monitor Github issues, so please raise a support request, as outlined below.

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
