### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'setPluginVersion' of null, js engine: hermes

### ISSUE THREAD

**Issue by kareemragab** [Anyline/anyline-ocr-react-native-module#178]
<img width="357" alt="Screenshot 2024-08-08 at 12 10 35 AM" src="https://github.com/user-attachments/assets/11f6c1f2-8274-4313-a1f2-6cae67fc5814">

version : "anyline-ocr-react-native-module": "^53.0.0",

When this happens after installing the library and trying to run the application ?

**Comment by kareemragab** [comment]
@berndkamplanyline 
Do you have any information about why this might happen?

**Comment by berndkamplanyline** [comment]
Hi @kareemragab,

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://support.anyline.com

---

Thank you so much!
