### ISSUE TITLE
App crashes while doing OCR scan

### ISSUE THREAD

**Issue by shubhnik** [Anyline/anyline-ocr-react-native-module#18]
While Barcode scanning runs without any issue, but the app crashes with following message when OCR scanning is selected:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager copyItemAtPath:toPath:options:error:]: source path is nil'
*** First throw call stack:
(0x19000afd8 0x18ea6c538 0x19000af20 0x190aa8dc0 0x1001156a0 0x101416784 0x196139f9c 0x196139b78 0x196b0c380 0x196486970 0x1964aad3c 0x1964adb68 0x19622ac24 0x1014179b0 0x102825a50 0x102825a10 0x10282ab78 0x18ffb90c0 0x18ffb6cdc 0x18fee6d94 0x191950074 0x19619f130 0x1000c0f08 0x18eef559c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```
###My config file's OCR section looks like this:
```
ocr: {
        "scanMode": "AUTO",
        "tesseractLanguages": "all",
        "traineddataFiles": ["trainedData/eng_no_dict.traineddata"],
        "charWhitelist": "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
        "validationRegex": "[A-Z0-9]{8}$",
        "isBrightTextOnDark": true
    }
```
Where am i doing wrong?

**Comment by JonasLaux** [comment]
Hi,

did you copy your trainingdata to the rigth directory ("trainedData/eng_no_dict.traineddata")?
More infos [here](https://documentation.anyline.io/toc/platforms/react-native/getting_started.html) at Section 'Add custom TrainData to the OCR Module'.

**Comment by shubhnik** [comment]
Hi @JonasLaux it seems the readable path is relative to www, at least in my case because it's working now after that modifications, Thanks :)
