### ISSUE TITLE
Execution failed for task ':app:compileMhqDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by PriyaDS1** [Anyline/anyline-ocr-react-native-module#182]
/Users/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:27: error: package undefined does not exist
import undefined.AnylinePackage;
                ^
/Users/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:119: error: cannot find symbol
      new AnylinePackage(),
          ^
  symbol:   class AnylinePackage
  location: class PackageList
Note: /Users/android/app/src/debug/java/com/mtekpro/seq/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileMhqDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

=>import io.anyline.reactnative.AnylinePackage;
changing manually but still automatically it is generating to import undefined.AnylinePackage; while building the app please help us on this using anyline-ocr-react-native-module version 54.0.0 and react-native version 0.68.2

**Comment by berndkamplanyline** [comment]
Hi @PriyaDS1,

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://support.anyline.com

---

Thank you so much!
