### ISSUE TITLE
Use React Components instead of native code for UI

### ISSUE THREAD

**Issue by Jpadilla1** [Anyline/anyline-ocr-react-native-module#23]
The reason for this is to be able to modify/add parts of the UI without having to touch native code and would allow for more customization.

**Comment by JonasLaux** [comment]
Sorry, is this a question?

**Comment by Jpadilla1** [comment]
No, it's just an idea to use React components to customize the UI. For example if I wanted to add a custom grid button, I would have to modify the native code on both platforms.

**Comment by JonasLaux** [comment]
Ok, now i get it. Good call, though. 
Rewriting the module to a more abstract design is on our RoadMap. 
At the moment we have a lot going on with other projects. But if we got more time, i will definitely plan in integrating this for a few sprints.
Thanks for suggesting!

**Comment by Jpadilla1** [comment]
Thank you!

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
