### ISSUE TITLE
AnylineOCR.setupScanViewWithConfigJson is undefined

### ISSUE THREAD

**Issue by samsiu2014** [Anyline/anyline-ocr-react-native-module#25]
![image](https://user-images.githubusercontent.com/26761164/29056292-7de78a9e-7c34-11e7-9500-fd9927d9d296.png)

i followed the instruction in the Quick Start Guide, but i still got this error, what can i do to fix it?
I just want to try the basic functions.
Thank You!

**Comment by JonasLaux** [comment]
Hi,
sorry but what exactly are you trying to do? Do you start the Examples App or do you implement it in you own environment? If so, can you please provide the most important pieces of your implementation.

**Comment by samsiu2014** [comment]
@JonasLaux  I just followed every steps in the Quick Start Guide.
I just change the project name and the license.
It shows me a overview page, but no matter which button(Barcode Scanner, Document Scanner) i clicked, it shows me the Anyline is undefined.

**Comment by JonasLaux** [comment]
And you installed the anyline-ocr-react-native-module and linked it?

**Comment by samsiu2014** [comment]
@JonasLaux  yes of coz, but i noticed that only android part is linked.
rnpm-install info Android module anyline-ocr-react-native-module is already linked

**Comment by JonasLaux** [comment]
Ok, i just tried a fresh build and it worked. I can't figure out, why this is not working on your side. Can you try going into the iOS folder and fire `pod update`. 
Then open the workspace in Xcode and try it from there.

**Comment by samsiu2014** [comment]
@JonasLaux Ok! Thank you so much!
I found out that the problem is related to the pod update.
After i reinstalled the pod, it is okay now.
```
rm -rf ~/.cocoapods/repos
pod setup
```

So the react-native link won't link for the ios right?

**Comment by JonasLaux** [comment]
Normally it should https://facebook.github.io/react-native/docs/linking-libraries-ios.html
