### ISSUE TITLE
When the user turns the flash On, Anyline doesn't turn it Off when finished

### ISSUE THREAD

**Issue by djmc** [Anyline/anyline-ocr-react-native-module#26]
With the flash configuration set to

```
flash: {
  mode: 'manual',
},
```

When the user turns on the flash, and then scans whatever it is (in this case, we're using it for energy meter reading), Anyline does not turn the Flash off when it is done. This native module also doesn't appear to provide any way for us to manually turn it off, which means we have to create an instance of the `react-native-camera-kit` in order to then turn off the flash.

**Comment by JonasLaux** [comment]
Yes, good point.
I will consider this in the next release! 
Thanks for mentioning

**Comment by JonasLaux** [comment]
Hi @djmc ,
can you provide some more information? On which platform is this an issue (only iOS, only Android, both)? On which phone(s) did it appear?

**Comment by Oblongmana** [comment]
@JonasLaux 

Could you re-open this issue?

I have this issue on the latest version of this library `3.19.0`, and can confirm the issue appears on the iPhone 6.

Time allowing, I may be able to test on iPad and Galaxy S7 as well, but can definitely confirm it's an issue on the iPhone 6

**Comment by JonasLaux** [comment]
Hi,
yes i see. it's not implemented on the onResult, just on the OK button. I will make a new build today. Thanks for mentioning
