### ISSUE TITLE
Conflict with gradle config for rn-firebase 

### ISSUE THREAD

**Issue by thomashermine** [Anyline/anyline-ocr-react-native-module#27]
When I try to build the app for android with react-native run-android, I get this error: 

`Could not find io.anyline:anylinesdk:3.17.0.
     Required by:
         AppName:app:unspecified > AppName:anyline-ocr-react-native-module:unspecified
`

So, I followed the [Advanced Topic page](https://documentation.anyline.io/toc/platforms/react-native/advanced.html) and added this to android/app/build.gradle :

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()

        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }

        maven {
          url 'https://anylinesdk.blob.core.windows.net/maven/'
        }
    }
}
```

... but this breaks RNFirebase, I get this error multiple times : 

`error: RNFirebaseAnalyticsPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
`

How can I configure build.gradle so that both rn-firebase and anyline-ocr-react-native-module works?

**Comment by JonasLaux** [comment]
Hi,
hmm very strange. And the error does apply by only adding the maven repo? So when you remove anyline from gradle, everything works fine?

**Comment by thomashermine** [comment]
My bad! 

I was 100% sure this error appeared right after installing Anyline - turns out I was on the wrong branch of my project repository.

This issue was totally unrelated to anyline-react plugin, it can be closed.
