### ISSUE TITLE
RN 0.47 compatibility - method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by thomashermine** [Anyline/anyline-ocr-react-native-module#28]
[createJSModule is no longer required on Android from React-Native 0.47.
](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)
Leaving the @Override marker on the method actually prevents building on Android with RN 0.47, with this error:

```
AnylinePackage.java:16: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

I was able to fix it by[ simply removing the @Override marker](https://github.com/thomashermine/anyline-ocr-react-native-module/commit/d4cc52a51491147e455e378a4737283047c241ea) - and it should maintain compatibility with previous version of RN, but I did not test anything beside RN 0.47.2

**Comment by JonasLaux** [comment]
Thanks for the advice! 
I will check everything for the next release!
