### ISSUE TITLE
NativeModules.AnylineSDKPlugin is undefined (iOS)

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#3]
worked fine in a new project, but in my existing project, i'm having trouble getting things linked up. Any ideas what could go wrong?

**Comment by matthiasgasser** [comment]
Hi! Could you please share a minimum example, which sports this error?

Thank you

**Comment by mvayngrib** [comment]
@matthiasgasser looks like i found my problem. react-native link doesn't seem to add libAnylineReact.a to the "Link Binary with Libraries" build phase. Once i added it manually, stuff started working.
