### ISSUE TITLE
[Android] cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz"

### ISSUE THREAD

**Issue by edcrampin** [Anyline/anyline-ocr-react-native-module#33]
Hi,

I seem to be having the same issue as #20, however the fix within that issue didn't work for me. Whenever I call Anyline.setupPromise and an Android device, this is the issue I receive:

```
E/art: dlopen("/data/app/*.*.*-1/lib/arm/libopencv_java3.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "libopencv_java3.so"...
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: *.*.*, PID: 24911
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "libopencv_java3.so"...
                      at java.lang.Runtime.loadLibrary(Runtime.java:371)
                      at java.lang.System.loadLibrary(System.java:988)
                      at at.nineyards.anyline.camera.AnylineBaseView.<clinit>(SourceFile:49)
                      at com.anyline.reactnative.EnergyActivity.onCreate(EnergyActivity.java:58)
                      at android.app.Activity.performCreate(Activity.java:5990)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Thanks.

**Comment by JonasLaux** [comment]
Hi, in which gradle file did you implement the fix? 
Can you post the important part of the gradle?

**Comment by edcrampin** [comment]
Tried placing in my android/app/build.gradle. File is as follows:

```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "***"
        minSdkVersion 17
        targetSdkVersion 26
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
           ...
        }
    }
    packagingOptions {
        pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
        pickFirst 'lib/x86/libgnustl_shared.so'
        pickFirst 'lib/*/libopencv_java3.so'
    }
    splits {
        abi {
            enable true
            reset()
            //enable enableSeparateBuildPerCPUArchitecture
            //universalApk false  // If true, also generate a universal APK
            include 'armeabi-v7a', 'x86'
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    ...
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'io.anyline:anylinesdk:3.17.0@aar'
    ...
}
```

**Comment by JonasLaux** [comment]
can you try an other architecture or a wildcard?

` pickFirst('lib/*/libgnustl_shared.so')`

**Comment by edcrampin** [comment]
I tried modifying it to this, not sure if this is what you were suggesting but still no luck:
```
    packagingOptions {
        pickFirst 'lib/*/libgnustl_shared.so'
        pickFirst 'lib/*/libopencv_java3.so'
    }
```

**Comment by JonasLaux** [comment]
Hey, 
can you provide some further information?
Like, which Device you'r facing this issue? Which gradle Version do you use? Do you start it with the react-native CLI or via Android Studio (if yes, which version)?

**Comment by edcrampin** [comment]
Hi Jonas,

This issue occurs with any Android device I've tested with and using Gradle 4.1. Tested from both react-native CLI and Android Studio (3.0.1). 

The app compiles and launches fine, just whenever I trigger setupPromise, the error above is thrown.

Thanks.

**Comment by edcrampin** [comment]
This might be related, I added "x86" into android.defaultConfig.ndk.abiFilters of the anyline-ocr-react-native-module build.gradle, as without this addition I received the error  `Cannot build for ABI: x86; no suitable splits configured: none; supported ABIs are: armeabi-v7a` when trying to run. Could this be related due to 32-bit/64-bit? Just a thought.

**Comment by marwakhalil** [comment]
Hello,
is there any progress for this error because i got it when testing the example application
Thanks

**Comment by JonasLaux** [comment]
Hi,
so i tried some scenarios and i think it's the Gradle Version. Can you try (just for fun) to downgrade Gradle to 3.x and check if this works?

**Comment by marwakhalil** [comment]
yes actually it's related to gradle version, i've downgrade the version and it works now thanks

**Comment by edcrampin** [comment]
@JonasLaux I've downgraded gradle version within my app, however getting this:

```
A problem occurred evaluating project ':anyline-ocr-react-native-module'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 4.1. Current version is 3.5.
```

How can I change minimum support gradle version for anyline-ocr-react-native-module?

**Comment by JonasLaux** [comment]
how did you downgrade your App's Gradle Version?
[Here](https://stackoverflow.com/a/33892937/2157717) is a good example. 
If this doesn't work, i think you need to fix the gradle wrapper, which you can find [here](https://stackoverflow.com/questions/43077386/gradle-error-minimum-supported-gradle-version-is-3-3-current-version-is-3-2).

**Comment by edcrampin** [comment]
Got that working, however now I'm receiving issues with some of my modules as they appear to require gradle 4.x due to using implementation() over compile()

```
A problem occurred evaluating project ':app'.
> Could not find method implementation() for arguments [project ':react-native-maps', build_41n98zifaojgryp59mm43g79v$_run_closure2$_closure18@619da3bc] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
```
It feels a little hacky having to manually change this however I'll try it out, unless there's a simpler way.

**Comment by JonasLaux** [comment]
yes, i will check if we can make any improvements on this to get rid of this workaround for future releases.

**Comment by edcrampin** [comment]
Building with Gradle 3.5 has not fixed the issue for me. I am still receiving

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: *.*.*, PID: 25712
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/*.*.*-1/lib/arm/libopencv_java3.so"...
```

**Comment by JonasLaux** [comment]
Can you please post your gradle/wrappers/gradle-wrapper.properties and your android/build.gradle?

**Comment by edcrampin** [comment]
gradle-wrapper.properties:
```
#Wed Dec 13 12:18:03 GMT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
#distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-all.zip
```

android/build.gradle:
```
buildscript {
    repositories {
        jcenter()
        //google()
        maven {
            url 'https://maven.google.com'
        }
    }
    dependencies {
        // classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
		maven { url "https://jitpack.io" }
                maven { url 'https://anylinesdk.blob.core.windows.net/maven/'}
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"

        }
        maven {
            url 'https://maven.google.com'
        }
        //google()
    }
}
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.2'
            }
        }
    }
}
```

**Comment by JonasLaux** [comment]
hmm, very strange. Does Gradle rebuild your project and asks for an update (in Android Studio)? I really can't reproduce it with 3.5, only with 4.4 i get the same error. 
Also, do you still have the pickFirst implemented?

**Comment by edcrampin** [comment]
It rebuilds my project, hasn't asked for an update though. My pickFirst setup is currently as follows, have tried playing around with different formats (including armeabi-v7a/x86 too) with no luck:

```
    packagingOptions {
        pickFirst('lib/*/libopencv_java3.so')
        pickFirst('lib/*/libgnustl_shared.so')
    }
```
To confirm, this should be under android/app/build.gradle, is that correct?

I've also tried running from gradle on the command line, and ./gradlew --version confirms I'm using 3.5 for this. Have tried cleaning caches for gradle to force a rebuild as well.

As a check too, are you running this on Android Simulator or on a real device? And would using x86 make any differences? I've been testing on both an x86 emulator image and armeabi-v7a physical device and both show the same issue, just with differences on the libopencv path used (lib/x86/libopencv_java3.so or lib/arm/libopencv_java3.so). I know that x86 isn't listed under abiFilters within the Anyline build.gradle, so just checking that I should be able to get this running on simulator too?

**Comment by edcrampin** [comment]
As a further update, I compared the files between the example application and my own application on the device, and it seems the libgnustl_shared.so that my own application is trying to use is different in size to the libgnustl_shared.so that the example application (that I managed to get working) is using, so I believe that for some reason the correct libgnustl_shared.so is not being packaged on build.

**Comment by edcrampin** [comment]
This has been resolved - issue seemed to be a couple of thing.

First I had a second ` compile 'io.anyline:anylinesdk:3.20.0@aar'` within my own project's app/build.gradle, not sure if I accidentally placed this here or if this was as a result of `react-native link`. Secondly I had to make sure within the Anyline project that this compile line was at the top of all dependencies, and within my own app's build.gradle that the Anyline react-native project was above everything else. This then meant that pickFirst selected the correct version of libgnustl_shared.so.

**Comment by raghavendramogeraya** [comment]
getting error while using the code 
```
const result = await AnylineOCR.setupPromise(
                JSON.stringify(MRZConfig),
                "MRZ"
            );

UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.noonpay-1/lib/arm/libopencv_java3.so"...

```

**Comment by raghavendramogeraya** [comment]
My Gradle version is 4.4.Is there any fix for this version as given in https://github.com/Anyline/anyline-ocr-react-native-module/issues/39#issuecomment-390928094?

**Comment by JonasLaux** [comment]
Hey, 
yes it will be in our next Release Anyline 6 on 07.12.
