### ISSUE TITLE
iPhoneX flash indicator placement

### ISSUE THREAD

**Issue by maximmcnair** [Anyline/anyline-ocr-react-native-module#37]
![img_0608](https://user-images.githubusercontent.com/1009787/38799661-0011034a-415d-11e8-97fe-da1a27ae3cd4.png)

**Anyline React-Native Plugin version:** 
3.19.1

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[ x ] iOS

**Current behavior:**
Flash toggle is currently rendered over the time on the iPhoneX 

**Expected behavior:**
It should take the layout of the iPhoneX into account and be placed lower.

**Steps to reproduce:**
Take photo and view placement of flash toggle

**Comment by JonasLaux** [comment]
Hey,
thanks for pointing it out! 
We will investigate the issue on the Iphone X. It has an other displays then the other Iphones, so i think we need to recalculate our coordinates. I will keep you updated.

**Comment by JonasLaux** [comment]
Hey, 

so we fixed the issue. It will be released with our 3.24 Release at the 15th of may.
