### ISSUE TITLE
Anyline (~> 3.23.1) doesn't exist

### ISSUE THREAD

**Issue by nicastelo** [Anyline/anyline-ocr-react-native-module#38]
**Anyline React-Native Plugin version:** 
3.23.1

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[ x ] iOS

**Current behavior:**
Error while running `pod install`

```
[!] CocoaPods could not find compatible versions for pod "Anyline":
  In Podfile:
    AnylineReact (from `../node_modules/anyline-ocr-react-native-module/ios`) was resolved to 3.23.1, which depends on
      Anyline (~> 3.23.1)

None of your spec sources contain a spec satisfying the dependency: `Anyline (~> 3.23.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Expected behavior:**
`pod install` runs correctly

**Steps to reproduce:**
Write the podfile and run `pod install`

**Other information:**
When cocoapods tries to download Anyline, the version resolved is `~> 3.23.1` as it's described in the podspec. The problem is that there is no version between 3.23.1 and 3.24. The last version published is the v3.23.0 (https://cocoapods.org/pods/Anyline).

**Comment by JonasLaux** [comment]
Hi, 
thanks for pointing it out. 
The podspec is now fixed to a stable version.

Thank you for pointing it out
