### ISSUE TITLE
Android: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz"

### ISSUE THREAD

**Issue by bvanleeuwen1995** [Anyline/anyline-ocr-react-native-module#39]
**Anyline React-Native Plugin version:** 
3.23.2

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
App crashes when called anyline setup functions

**Expected behavior:**
Opening the scanner as normal

**Steps to reproduce:**
Calling Anyline.setup function in React Native

**Related code:**
build.gradle
```
android {
    compileSdkVersion 26
    buildToolsVersion "26.1.0"

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride = versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    packagingOptions {
        pickFirst('lib/*/libgnustl_shared.so')
        pickFirst('lib/*/libopencv_java3.so')
    }

    dexOptions {
        jumboMode true
    }
}


dependencies {
    compile project(':anyline-ocr-react-native-module')
    compile project(':react-native-video')
    compile project(':react-native-fs')
    compile project(':react-native-vector-icons')
    compile project(':react-native-camera')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-device-info')
    compile project(':react-native-photo-view')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

**Other information:**
I have tried the answers from previous bug reports, sadly this issue still exists for me, is there anything that I have missed so far?

**Comment by JonasLaux** [comment]
Hey,

could you please provide the Call in JS (your Anyline setup function and the parameters).
Also, could you provide the Crashlog of Logcat?

**Comment by bvanleeuwen1995** [comment]
Hello,

Thank you for the quick response, really appreciated :)

The JS code that calls Anyline is very simple: 
`showAnyLine() {
        AnylineOCR.setup(
            this.scannerConfig,
            'BARCODE',
            this.onSuccessFullRead,
            this.onFailedRead
        );
    }`

The config file:
`{
license: "....",
options: {
        captureResolution: '1080',

        cutout: {
            style: 'rect',
            alignment: 'center',
            maxWidthPercent: '90%',
            maxHeightPercent: '90%',
            ratioFromSize: {
                width: 100,
                height: 100
            },
            strokeWidth: 1,
            cornerRadius: 3,
            strokeColor: 'FFFFFF',
            outerColor: '000000',
            outerAlpha: 0.5
        },
        flash: {
            mode: 'auto',
            alignment: 'bottom_right'
        },
        visualFeedback: {
            style: 'rect',
            strokeColor: '0099FF',
            fillColor: '220099FF',
            animationDuration: 150
        },
        beepOnResult: true,
        vibrateOnResult: false,
        blinkAnimationOnResult: true,
        cancelOnResult: true,
        doneButton: {
            title: 'Cancel',
            type: 'rect',
            cornerRadius: 0,
            textColor: 'FFFFFF',
            textColorHighlighted: 'CCCCCC',
            fontSize: 33,
            fontName: 'HelveticaNeue',
            positionXAlignment: 'center',
            positionYAlignment: 'bottom',
            offset: {
                x: 0,
                y: -88
            }
        }
    }}`

And the full logcat error:
`FATAL EXCEPTION: main
                                                                   Process: ..., PID: 21808
                                                                   java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/...-2/lib/arm/libopencv_java3.so"...
                                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                       at java.lang.System.loadLibrary(System.java:1567)
                                                                       at at.nineyards.anyline.camera.AnylineBaseView.<clinit>(SourceFile:49)
                                                                       at com.anyline.reactnative.BarcodeActivity.onCreate(BarcodeActivity.java:45)
                                                                       at android.app.Activity.performCreate(Activity.java:6912)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by JonasLaux** [comment]
Hey, 

i'm quite sure it's related to [this](https://github.com/Anyline/anyline-ocr-react-native-module/issues/20#issuecomment-303377234).

**Comment by bvanleeuwen1995** [comment]
I found that issue, but sadly that didn't fix it for me, I added it to the bottom of my android/app/build.gradle, but still I got the same errors.

**Comment by Johny8811** [comment]
Hello guys, I have same error.

**Anyline:** v. 3.23.2
**RN:** v. 0.51.0
**Gradle:** v. 4.1
**Gradle plugin:** v. 3.0.1

**Anyline config:**
`license: '...',
  options: {
    'captureResolution': '1080p',
    'cutout': {
      'style': 'rect',
      'alignment': 'top_half',
      'strokeWidth': 2,
      'cornerRadius': 4,
      'strokeColor': 'FFFFFF',
      'outerColor': '000000',
      'outerAlpha': 0.3,
    },
    'flash': {
      'mode': 'manual',
      'alignment': 'bottom_right',
    },
    'beepOnResult': true,
    'vibrateOnResult': true,
    'blinkAnimationOnResult': true,
    'cancelOnResult': true,
    'reportingEnabled': true,
    'visualFeedback': {
      'style': 'CONTOUR_RECT',
    },
  },
`

**Gradle file:**
`
android {
    compileSdkVersion 26
    buildToolsVersion "27.0.1"

    defaultConfig {
        applicationId "com.meterie"
        minSdkVersion 17
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    packagingOptions {
        pickFirst('lib/*/libgnustl_shared.so')
        pickFirst('lib/*/libopencv_java3.so')
    }
}
`

I think that problem is in version of gradle or gradle plugin, because when I upgraded gradle and gradle plugin in your example git I got same error.

**Comment by JonasLaux** [comment]
hey,
yes you're right. It seems that the pickFirst is behaving differently in newer gradle Versions.
We will investigate this more, but for a quickfix i would recommend using gradle 2.x

**Comment by Johny8811** [comment]
Okey, thanks for quick answer.

**Comment by bvanleeuwen1995** [comment]
Is there any news when this will be fixed? We want to use the last gradle version, but sadly the SDK version crashses.

**Comment by JonasLaux** [comment]
Hey,
we have a safe workaround for this one. Can you please insert these correct libs folder (unzipped) 
[jniLibs.zip](https://github.com/Anyline/anyline-ocr-react-native-module/files/2025929/jniLibs.zip)
into .../yourRNApp/android/app/src/main
so you get  .../yourRNApp/android/app/src/main/jniLibs .
Also, you can remove the pickFirsts from your gradle.
Unfortunately, this is the only workaround i can provide at the moment. We have to wait, till gradle provides a better way to deal with conflicts or React updates their libs.

**Comment by bvanleeuwen1995** [comment]
Hi Jonas,

Thanks for the reply, I have tested your recommendation, and it seems to be all working right now.

**Comment by JonasLaux** [comment]
Glad to hear. If you still have corresponding problems, feel free to reopen this issue.

**Comment by Johny8811** [comment]
Hi Jonas, I can confirm that everything works right for me too.
