### ISSUE TITLE
example app crashes

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#4]
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
```
![image](https://cloud.githubusercontent.com/assets/83948/21763513/342017e6-d699-11e6-830d-37c5b6742a6c.png)

**Comment by JonasLaux** [comment]
Hi,
it seems like the controller has no view initialized. 
Can you please share some more details? Did you use the plain example App or did you change something?

**Comment by mvayngrib** [comment]
@JonasLaux looks like i found my problem. react-native link doesn't seem to add libAnylineReact.a to the "Link Binary with Libraries" build phase. Once i added it manually, stuff started working.
