### ISSUE TITLE
Update Android gradle file

### ISSUE THREAD

**Issue by bvanleeuwen1995** [Anyline/anyline-ocr-react-native-module#43]
Please see this iOS issue: https://github.com/Anyline/anyline-ocr-react-native-module/issues/42

The same issue exists for Android also, the gradle file has not been updated to include the latest SDK version, which gives build errors.

**Comment by JonasLaux** [comment]
Hey,
i don't know why you are getting old versions, but i can assure you, if you download the package 3.24 from npm both [podspec](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/plugin/ios/AnylineReact.podspec#L24) and [gradle](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/plugin/android/build.gradle#L60) are updated.
