### ISSUE TITLE
Make toast optional

### ISSUE THREAD

**Issue by bvanleeuwen1995** [Anyline/anyline-ocr-react-native-module#44]
Hello,

The toast when a scan has been made that show the text "Image saved to" and the file location should be made optional, for now I have commented the line in the DocumentActitvity.java.

A new variable in the scan config is a good option to add to the current list in order to hide this toast message.

**Comment by ale-anyline** [comment]
Hi Bob,
Thanks a lot for the suggestion. We'd definitely like to do this, however we don't know exactly when we'll be able to get around to it. Since you already made your implementation, could you please submit a PR? We would really appreciate it.

**Comment by bvanleeuwen1995** [comment]
Hi,

I have not really implemented a fix ore variable, but rather commented the line that showed the toast message.

If I do find some time I will try if I can make it a variable and create a pull request.

**Comment by ale-anyline** [comment]
Great! Thank you very much.

**Comment by bvanleeuwen1995** [comment]
This issue can be closed since the code has been implemented and merged
