### ISSUE TITLE
 Could not find common.jar (android.arch.core:common:1.0.0) (Compile Time Error) 

### ISSUE THREAD

**Issue by vjijardar** [Anyline/anyline-ocr-react-native-module#45]
Getting Error When Run code on Android 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':anyline-ocr-react-native-module'.
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      **https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar**

**Anyline React-Native Plugin version:** 
 anyline-ocr-react-native-module: "^3.24.0"

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[x] general question

[x] Android
[ ] iOS

**Current behavior:**
   https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar
**after Open on Web**
**https://repo.jfrog.org/artifactory/libs-release-bintray/android/arch/core/common/1.0.0/common-1.0.0.jar?referrer
**Response** 
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}**

![screenshot 128](https://user-images.githubusercontent.com/19422534/41159635-cef4da76-6b4a-11e8-968b-657ce33490a7.png)

**Environment**:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.2.0
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

**Packages**: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by JonasLaux** [comment]
Hi,

this is related to the Google Maven. It seems like .you are using an different gradle Version. Which Gradle Version do you have? Also, can you provide your yourProject/android/build.gradle?

**Comment by vjijardar** [comment]
Hey @JonasLaux ,

Please find the attachment  of build.dradle inside ZIP

[build.zip](https://github.com/Anyline/anyline-ocr-react-native-module/files/2086655/build.zip)

**Comment by vjijardar** [comment]
@JonasLaux  any Update ..????

**Comment by JonasLaux** [comment]
Hey,
sorry, i did not work during the weekend. This is the wrong gradle file you uploaded. This gradle file should be in /android/**app/**build.gradle, i need the /android/build.gradle

**Comment by vjijardar** [comment]
Hello,

PFA  **/android/build.gradle**

[androidGradle.zip](https://github.com/Anyline/anyline-ocr-react-native-module/files/2092842/androidGradle.zip)

**Comment by JonasLaux** [comment]
Can you please try adding the Google Repo like [so](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/android/build.gradle#L19)

**Comment by vjijardar** [comment]
@JonasLaux  okay i'll try this n let u know what happen.

**Comment by vjijardar** [comment]
@JonasLaux    

   **maven { url "https://maven.google.com" }
    maven { url "$rootDir/../node_modules/react-native/android" }
    jcenter() **
 
Its Solve the Comman.jar issue but after that i got new issue is:

**FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find io.anyline:anylinesdk:3.25.0.
     Required by:
         DigirecordsLite:app:unspecified > DigirecordsLite:anyline-ocr-react-native-module:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.698 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html**

**Comment by JonasLaux** [comment]
Hi,
please add the Anyline Maven Repo like [here](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/android/build.gradle#L27). Additional Information are documented [here](https://documentation.anyline.com/toc/platforms/react-native/advanced.html).
