### ISSUE TITLE
[android] Capture Button Not Showing (continue scanning the doc but failed )

### ISSUE THREAD

**Issue by vjijardar** [Anyline/anyline-ocr-react-native-module#47]
Hello,

I'm using the latest version of anyline sdk. sample code i'm download from Github but it doesn't show the capture button

**Comment by JonasLaux** [comment]
Hey,

I'm not quite sure what you mean with capture Button. If you mean, that there should be a Button to press during the Scan, then i can tell you, there is no capture Button. Anyline works with automatically detection. It scans without a Button to press. When you hold the Cutout over the designated scan target, it will trigger and give you the result.

**Comment by vjijardar** [comment]
what i'm trying to say you i'm downloaded the iOS app on Mobile if the document scanner is not scan automatically  so there is show camera icon to capture the pic and after that crop it. but in react native the camera icon not showing. 
See the Attachment in center bottom Camera Button.
![unnamed](https://user-images.githubusercontent.com/19422534/41599098-c4b09de0-73ef-11e8-9646-ab1fb71c7cf1.jpg)

**Comment by JonasLaux** [comment]
Hey,

yes, that's a special implementation (showcase) for our Document Scanner. Everything in there is natively build (Android and iOS). Also, the cropping is an App implementation, so not included in our library. Till now, we also don't have the manual button as configuration in our React-Native plugin. But it is available native ([iOS](https://documentation.anyline.com/toc/platforms/ios/modules/document.html#trigger-manual-corner-detection), [Android](https://documentation.anyline.com/toc/platforms/android/modules/document.html#manual-corner-detection)). 
Unfortunately, implementing this in our React-Native plugin is not on our Roadmap soon. If this a critical feature for you, feel free to issue a pull-request for it. Corresponding files are [Android](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/plugin/android/src/main/java/com/anyline/reactnative/DocumentActivity.java), [iOS](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/plugin/ios/AnylineDocumentScanViewController.m).

**Comment by vjijardar** [comment]
what I'm facing issue is  the document scanner continue scanning the doc its failed to give the result.

PFA video 
[f1153b39-ac5d-4f5c-b1b0-ce301d66567d.zip](https://github.com/Anyline/anyline-ocr-react-native-module/files/2115382/f1153b39-ac5d-4f5c-b1b0-ce301d66567d.zip)

**Comment by JonasLaux** [comment]
Hey,

can you please create a new issue next time for a different question? Thanks you :) 
The problem you're facing, is because you hold the device too close to the document (so it doesn't fit on the screen). If you look [here](https://anyline.com/products/document-scanner-sdk/), at the top is a demo how to use it. Also, there is a blue box during the Document Scan at the top, giving you feedback. It should tell you, that you're too close.
