### ISSUE TITLE
Image Scan and Capture Successfully but Not Saved Show Error (1529676296198DOCUMENT_OUTLINE_NOT_FOUND) 

### ISSUE THREAD

**Issue by vjijardar** [Anyline/anyline-ocr-react-native-module#48]
**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[x] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
DocumentActivity: error image saved to /data/data/com.digirecordslite/cache/error/1529676296198DOCUMENT_OUTLINE_NOT_FOUND.jpg

**Expected behavior:**
Image to Local cache 

**Related code:**

06-22 19:34:54.734 21960-22353/com.W/ANYLINE_CORE: 2018-06-22 19:34:54,734594 anyline_core.cpp:85 WARNING: This license is valid until: 2018-07-13
06-22 19:34:56.574 21960-21960/com.D/AnylineImage: Image saved in 375 ms
06-22 19:34:56.574 21960-21960/com.D/DocumentActivity: error image saved to /data/data/com./cache/error/1529676296198DOCUMENT_OUTLINE_NOT_FOUND.jpg

**Comment by JonasLaux** [comment]
Hey,
Which Device do you use and how do you save the image? 
I don't think that the path is correct, especially beginning "/data/data/".

**Comment by vjijardar** [comment]
Hello JonasLaux,
I'm using Sony Xperia D5322 Android Version 5.1.1.

Image is saving by DocumentActivity i'm not doing any change.

**Comment by JonasLaux** [comment]
Hey,

so do get you right. You want the error image to be located at a different location?

**Comment by JonasLaux** [comment]
Hey,

how does it show you, that it's scanned correctly?
In this function, the scan process is goes in during the scan, if the current process is not properly done. Are you sure, that you are scanning the document correctly? Is the Visual Feedback green or red?

**Comment by JonasLaux** [comment]
Hi,

since there is no response, i am considering this as solved. If you have still issues, feel free to reOpen the ticket.
