### ISSUE TITLE
scan screen slow to appear

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#5]
from issuing Anyline.setupScanViewWithConfigJson to the appearance of the scanning screen takes two or more seconds.

**Comment by JonasLaux** [comment]
Hi,
can you please provide some more information. Do you use the example App or is it in your own context? If so, please provide a code snippet. 
Thanks

**Comment by mvayngrib** [comment]
@JonasLaux the performance is the same in my app and the example app. Here's a gif of the example app (i'm using [Touchpose](https://github.com/toddreed/Touchpose) to record the touches:

![anyline](https://cloud.githubusercontent.com/assets/83948/21983766/c678113a-dbc0-11e6-8f99-4ddd370645ad.gif)

i'm using an iphone 6+ with iOS 10.1.1. This is how i'm using touchpose:

1. add [QTouchposeApplication.h](https://github.com/toddreed/Touchpose/blob/master/Touchpose%20Example/Source/QTouchposeApplication.h) and [QTouchposeApplication.m](https://github.com/toddreed/Touchpose/blob/master/Touchpose%20Example/Source/QTouchposeApplication.m) to the example project

2.
```sh
$ git diff ios/Anyline
diff --git a/example/Anyline/ios/Anyline/AppDelegate.m b/example/Anyline/ios/Anyline/AppDelegate.m
index a5697dd..e462cd3 100644
--- a/example/Anyline/ios/Anyline/AppDelegate.m
+++ b/example/Anyline/ios/Anyline/AppDelegate.m
@@ -11,6 +11,7 @@
 
 #import "RCTBundleURLProvider.h"
 #import "RCTRootView.h"
+#import "QTouchposeApplication.h"
 
 @implementation AppDelegate
 
@@ -20,6 +21,9 @@
 
   jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
 
+  QTouchposeApplication *touchposeApplication = (QTouchposeApplication *)application;
+  touchposeApplication.alwaysShowTouches = YES;
+
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                       moduleName:@"Anyline"
                                                initialProperties:nil
diff --git a/example/Anyline/ios/Anyline/main.m b/example/Anyline/ios/Anyline/main.m
index 3d767fc..7a4b927 100644
--- a/example/Anyline/ios/Anyline/main.m
+++ b/example/Anyline/ios/Anyline/main.m
@@ -10,9 +10,12 @@
 #import <UIKit/UIKit.h>
 
 #import "AppDelegate.h"
+#import "QTouchposeApplication.h"
 
 int main(int argc, char * argv[]) {
   @autoreleasepool {
-    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
+    return UIApplicationMain(argc, argv,
+                             NSStringFromClass([QTouchposeApplication class]),
+                             NSStringFromClass([AppDelegate class]));
   }
 }
```

let me know if i can provide any additional information!

**Comment by JonasLaux** [comment]
Yes, this is because the initialisation of the anyline module and of the camera. You'r right, there could be a better performance, but it would take two different calls to initialise the module and afterwards build the view on native modules in the wrappers. What could be done is to move the initialisation to an other lifecycle method (eg in iOS from viewDidLoad to viewDidAppear). With that the whole performance would not change, but by pressing on the button, there would appear a black screen till the process is finished. I consider this as an improvement.
Thanks for suggesting.

**Comment by mvayngrib** [comment]
@JonasLaux hm, i think I followed that mostly. Running the initialization separately (earlier) sounds like a step in the right direction. I wonder why I don't have this problem with react-native-camera, and another ocr module I tried out. Have you profiled the initialization by any chance to see which part is the bottleneck?

**Comment by JonasLaux** [comment]
Yes, we did detect a bottleneck on the SDK side which we get rid of in the next release 3.8.2 coming in February. Still, thank you call attention to it!

**Comment by mvayngrib** [comment]
@JonasLaux awesome! will keep an eye out

**Comment by mvayngrib** [comment]
@JonasLaux this still seems to be an issue in the latest version :(

**Comment by JonasLaux** [comment]
@mvayngrib Yes, we improved some processes on the camera startup. But still there is a lot going on when starting Anyline. Especially at our Wrappers, this causes some delay that we can't avoid.

**Comment by mvayngrib** [comment]
@JonasLaux can we do what u said earlier about separating `init` from `show` so the developer can hide `init` behind some loading screen?

**Comment by JonasLaux** [comment]
@mvayngrib yes indeed, this would be a great improvement. The thing is, we are fully occupied on many different projects right now, but the Feature for the react-native Wrapper is on our Roadmap though. If you want to have a fast solution for it, always feel free to send us a pull-request.
