### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by brunoschuermans** [Anyline/anyline-ocr-react-native-module#53]
**Anyline React-Native Plugin version:** 
3.26

**I'm submitting a ...**  
[* ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ *] Android
[ ] iOS

**Current behavior:**
When running react-native run-android i get:

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :anyline-ocr-react-native-module.
     Required by:
         project :app
      > Unable to find a matching configuration of project :anyline-ocr-react-native-module: None of the consumable configurations have attributes.

**Comment by JonasLaux** [comment]
Hey,
Please integrate our sdk in your android app. You see an example at [Error: Could not find io.anyline:anylinesdk](https://documentation.anyline.com/toc/platforms/react-native/advanced.html)
