### ISSUE TITLE
Project native from scratch not running for the first time

### ISSUE THREAD

**Issue by brunoschuermans** [Anyline/anyline-ocr-react-native-module#55]
After having followed the steps to init the app with the dependency:

react-native init passwordreader
npm i anyline-ocr-react-native-module
react-native link

I try to run 
react-native run-android

and i get:

* What went wrong:
A problem occurred evaluating project ':anyline-ocr-react-native-module'.
> Could not find method google() for arguments [] on repository container.

if i change the version of my gradle wrapper to 4.5 i get:

* What went wrong:
A problem occurred evaluating project ':anyline-ocr-react-native-module'.
> Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by JonasLaux** [comment]
Please add the google repository to your app/android/build.gradle like [so](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/android/build.gradle#L19)

**Comment by brunoschuermans** [comment]
Doesn't work.
We wanted to buy your tool but your documentation and "example" about react-native is terrible.

**Comment by JonasLaux** [comment]
could you post the content of your android/build.gradle and android/app/build.gradle

**Comment by brunoschuermans** [comment]
put a clean running example from scratch please, would be better for everyone who would be interested.
let me know when it works
thx

**Comment by brunoschuermans** [comment]
and would be good that it work with expo also if you want that your product has success with react-native

**Comment by JonasLaux** [comment]
Hey,
as i said, this is not a normal RN-Plugin, it's a wrapper around our product. That our OCR Machine works (and the neural networks and pre/postprocessing in C++), it needs native dependencies. Expo is plain javascript (you can't even use React-Natives AndroidPermissions in it), so this will never work (except you use [ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit). 

The example in this Repo is working with minimal setup. Also, building a new App from skretch is described in the ReadMe. If you still having issues (e.g. with the google repository, which is a standardized step in an android dependency App), i'm happy to help you with a error description.
