### ISSUE TITLE
Pod install / update installs deprecated version of React

### ISSUE THREAD

**Issue by llanginger** [Anyline/anyline-ocr-react-native-module#57]
**Anyline React-Native Plugin version:** 
3.27.1
React native version 0.57.1

**I'm submitting a ...**  
[x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[x ] iOS

**Current behavior:**
`pod update` or `install` result in react (v 0.11.0) being installed via Cocoapods. This is highly problematic and causes the build to fail

**Expected behavior:**
That the install process be agnostic of the user's preferences for how React / other native libraries are managed

**Steps to reproduce:**
`react-native init someProject`, cd into it
Follow the installation instructions listed in this repo
`rm -rf node_modules/`
`yarn install`
`react-native run-ios`

**Other information:**
I Have tried simply removing traces of React from my Pods folder but that resulted in the following error:

[path-to]/node_modules/anyline-ocr-react-native-module/ios/AnylineSDKPlugin.h:3:9: 'RCTBridgeModule.h' file not found

Any help would be greatly appreciated!

-Leo

**Comment by JonasLaux** [comment]
Hey, 
can you please explain a little bit more, what your build error is and why you remove your node_modules?
Also, it should use your react-native podspec from the node_modules, not the one from cocoapods.

**Comment by llanginger** [comment]
Hey Jonas,

Thanks for responding so quickly! I’ll reproduce the error in a couple of hours when I’m at my desk but just in the meantime, I simply forgot to include the `yarn install` step - the error occurs regardless of whether I delete + reinstall my node modules and in my original post I just wanted to clarify that HAD tried doing that step!

**Comment by bvanleeuwen1995** [comment]
Could you maybe also supply your podfile? I have had some issues with RN and podfile, but it was down to a old pod that was no longer in RN

**Comment by llanginger** [comment]
So sorry for the delayed response.

The issue was on my end and was indeed podfile-related. I have now successfully integrated Anyline both into a fresh `react-native init` project and my existing project!

**Comment by ale-anyline** [comment]
Thanks for the feedback, Leo :)
