### ISSUE TITLE
respect captureResolution and/or ...

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#6]
I don't think captureResolution is being respected at the moment, at least on iOS.

The react-native bridge is really inefficient at transferring images > 100KB. I see a couple of ways this could be handled (these are not mutually exclusive):
1. respect capture resolution
2. add a `quality` option, like [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) does, and scale the image accordingly. An excerpt from image picker's code:
```obj-c
if ([[[self.options objectForKey:@"imageFileType"] stringValue] isEqualToString:@"png"]) {
    data = UIImagePNGRepresentation(image);
}
else {
    data = UIImageJPEGRepresentation(image, [[self.options valueForKey:@"quality"] floatValue]);
}
```
3. Return only the imagePath + fullImagePath and leave the extraction of the image from the disk to the developer. This would allow the result to be returned asap. This is definitely a good option to have.

**Comment by danielalbertini** [comment]
Thx we missed that one in the iOS documentation. Yes for certain modules there are some paramters fixed.

For Energy:
- Capture Resolution is fixed to 1080
- Cutout Width & Cutout Height
- Cutout Alignment should be set to TOP with a little offset, as this reduces reflections

We have option 3 in our Cordova Wrappers. I don't know why we are doing both right now in ReactNative (returning a path & returning a base64 string). Maybe a requirement by another customer. 

@JonasLaux will be able to clarify that when he is back next week.

**Comment by mvayngrib** [comment]
@danielalbertini great, i'll wait for @JonasLaux

**Comment by JonasLaux** [comment]
Hi,
yes you're right on this one. We got some issues on Android getting the image from the Path, so we decided on a workaround with the base64 string. This should be reduced to only the imagePath + fullImagePath. We will plan it on the next sprint to fix the resultView, thanks for mentioning.
