### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'

### ISSUE THREAD

**Issue by andileka** [Anyline/anyline-ocr-react-native-module#60]
When I create a new project and follow all the steps to implement anyline-ocr-react-native-module and run it in android  I get this error 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:anyline-ocr-react-native-module] C:\Users\User\Desktop\eenn\tttttttttttt\node_modules\anyline-ocr-react-native-module\android\build\intermediates\manifests\full\debug\AndroidManifest.xml as the library might be using APIs not available in
16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 17,
                or use tools:overrideLibrary="com.anyline.reactnative" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
24 actionable tasks: 1 executed, 23 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by JonasLaux** [comment]
Hey,
as the error says, your minSDK Version is too small. Please increase it to 17, like [here](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/android/build.gradle#L6)
I will make this more clear in the ReadMe. Thanks.

**Comment by andileka** [comment]
Hi Jonas ,
I increase minSDK to 17 and now I'M geting this error :

Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\68.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\70.jar, C:\Uss\transforms\dexBui                                                                                                                                                                                                                                                     uild\intermediates\transforms\dexBuilder\delder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\ttttt\android\app\build\intermediates\transfotttttttttt\android\                                                                                                                                                                                                                                                     op\eenn\tttttttttttt\android\app\build\inteapp\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\de\Users\User\Desktop\eenn\tttttttttttt\androbug\76.jar, C:\User                                                                                                                                                                                                                                                     \debug\85.jar, C:\Users\User\Desktop\eenn\ts\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\bui
ld\intermediates\tr
lder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\tt
ttttt
ttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms
\dexB
uilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop\eenn\
ttttt
lder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\tttttttttttt\antt                                                                                                                                                                                                                                                                             deb\7.t\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilderoid\bl\d                                                                                                                                                                                                                                                                             .jaUs\ebug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop\eenn\tttttttttttt\anbuimeedr                                                                                                                                                                                                                                                                             \Useselder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\ttttttttttttt                                                                                                                                                                                                                                                                    dexBuidtttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transformttttttts\de                                                                                                                                                                                                                                                                    dexBuirxBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop\eentttttt\n\tt                                                                                                                                                                                                                                                                    dexBuidlder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\tt
tt
tttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transfo
rm
s\dexBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop
\e
lder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\tt
tt
ttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transf
oD
rms\dexBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Deskt
oe
lder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\ttnn\                                                                                                                                                                                                                                                                transtttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediater\Dess\t                                                                                                                                                                                                                                                                termeransforms\dexBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\UsersC:\Us\Us                                                                                                                                                                                                                                                                app\blder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\ee
nld
n\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermedia
t3.
es\transforms\dexBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\U
s\a
lder\debug\70.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\79.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\80.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\81.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\82.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\83.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\84.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\86.jar, C:\Users\User\Desktop\eenn\tttttttttttt\android\app\build\intermediates\transforms\dexBuilder\debug\88.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JonasLaux** [comment]
https://stackoverflow.com/questions/46267621/unable-to-merge-dex

**Comment by andileka** [comment]
:(
It's giving me another error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JonasLaux** [comment]
https://stackoverflow.com/questions/36561103/apptransformclasseswithmultidexlistfordebug-failed

**Comment by JonasLaux** [comment]
can you post the whole log from the crash?

**Comment by andileka** [comment]
ok 

I also changed Button to TouchableOpacity 
because it gave me an error
 

Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
nextCleanInternal
    JSONTokener.java:116
nextValue
    JSONTokener.java:94
<init>
    JSONObject.java:159
<init>
    JSONObject.java:176
scan
    AnylineSDKPlugin.java:152
routeScanMode
    AnylineSDKPlugin.java:110
setupPromise
    AnylineSDKPlugin.java:104
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764

**Comment by JonasLaux** [comment]
So, the error is throwing in this line:
https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/plugin/android/src/main/java/com/anyline/reactnative/AnylineSDKPlugin.java#L152
It seems, that you don't pass a config. What's your implementation in JS?

**Comment by andileka** [comment]
Was a mistake of mine thanks for the help :)
