### ISSUE TITLE
Android - Could not find io.anyline:anylinesdk:4

### ISSUE THREAD

**Issue by maximmcnair** [Anyline/anyline-ocr-react-native-module#61]
**Anyline React-Native Plugin version:** 
4.0.0

**I'm submitting a ...**  
[ x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
Anyline fails to be installed when running `react-native run-android`.
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find io.anyline:anylinesdk:4.
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/4/anylinesdk-4.pom
      https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/4/anylinesdk-4.aar
      https://jcenter.bintray.com/io/anyline/anylinesdk/4/anylinesdk-4.pom
      https://jcenter.bintray.com/io/anyline/anylinesdk/4/anylinesdk-4.aar
  Required by:
      project :app > project :anyline-ocr-react-native-module
```

**Comment by ale-anyline** [comment]
Hi Max,
Sometimes, the project gradle overrides the plugin gradle repository entry.
To solve this issue, add the following lines to your project gradle file:

allprojects {
    repositories {
        ...
        maven { url 'https://anylinesdk.blob.core.windows.net/maven/'}
        ...
    }
}

**Comment by maximmcnair** [comment]
Missed this in the docs. Thanks for the fast reply.

**Comment by ditas3004** [comment]
Helooo..

I am having trouble integrating Anyline with react native

i'm using "react-native": "0.59.1" and "anyline-ocr-react-native-module": "^13.1.0"

after run react-native run-android 

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find io.anyline:anylinesdk:13.
  Searched in the following locations:
    - https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/13/anylinesdk-13.pom
    - https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/13/anylinesdk-13.aar
    - https://jcenter.bintray.com/io/anyline/anylinesdk/13/anylinesdk-13.pom
    - https://jcenter.bintray.com/io/anyline/anylinesdk/13/anylinesdk-13.aar
  Required by:
      project :app > project :anyline-ocr-react-native-module
