### ISSUE TITLE
ios build issue

### ISSUE THREAD

**Issue by raghavendramogeraya** [Anyline/anyline-ocr-react-native-module#64]
Installed SDK for Android and it's working fine. Now trying to install SDK for ios, followed the below steps:

Added below lines in Pod file: 
```
pod 'React', :path => '../node_modules/react-native'
  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

```
in ios folder, executed the 'pod install' command.
Now when I build, getting below error:
 ```
/Volumes/Development/reactnative/Anylineapp/node_modules/react-native/React/Modules/RCTDevSettings.mm:21:9: 'RCTPackagerClient.h' file not found
```
Please help me to setup the SDK for ios.

**Comment by raghavendramogeraya** [comment]
Hello Anyline team,
Any updates?

**Comment by JonasLaux** [comment]
Hey,
sorry for coming back to you so lately. Can you provide some more Information? Which versions of React and React-Native are you using? This seems to be a problem with the React Pods...
Already under discussion https://github.com/facebook/react-native/issues/17799.
Can you try adding DevSupport to your Pod File, like [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies)?

**Comment by raghavendramogeraya** [comment]
Hi,
I have tried it earlier, but it's not working. Here is the version details which Ia m using now:
react-native-cli: 2.0.1
react-native: 0.55.4
Xcode: 9.4

Please let me know if you need any additional info.

**Comment by raghavendramogeraya** [comment]
I run pod install because pod update updates all other pods also.

**Comment by JonasLaux** [comment]
hmyeah, 
unfortunately it's a problem with React-Native not with Anyline. 
But yes, because we are using React via Pods, this is coming up... 
The thing is, i can't really help with this issue, because i have not enough knowledge about the codebase of React-Native.
Is there no working solution in this thread?
https://github.com/facebook/react-native/issues/17799

**Comment by raghavendramogeraya** [comment]
Tried removing 'pod 'React', :path => '../node_modules/react-native'' in podfile because react is already linked manually. But it throws the error (attached screenshot) in AnylineSDKPlugin()
![screen shot 2018-11-20 at 12 59 16 pm](https://user-images.githubusercontent.com/41561410/48757973-7d9d3500-ecc4-11e8-81ab-07b9bda032b5.png)

**Comment by JonasLaux** [comment]
okay
in this example, the promise call behaves different then in our example App with Cocoapods.
I will have a look

**Comment by PhiMue** [comment]
Hello,

Could you please try to setup and run our Example app? This might give us some insights about the problem.

- Go to: https://github.com/Anyline/anyline-ocr-react-native-module/tree/master/example/RNExampleApp and run the following commands "npm run reinstall" and "npm run reinstall-pods"
- After it was installed successfully, please navigate to the iOS folder of the example app, and open "RNExampleApp.xcworkspace" in Xcode --> https://github.com/Anyline/anyline-ocr-react-native-module/tree/master/example/RNExampleApp/ios 
- Setup your developer certificate and try to run it on your device.

Can you please comment if it worked for you, and if not, please post your error messages - and where you got them.

Thank you very much!

**Comment by raghavendramogeraya** [comment]
Your example app is working fine for me. But when I install the SDK in my actual project it gives the error.

**Comment by raghavendramogeraya** [comment]
Example app is working fine for me. I am able to scan the card(MRZ). But when I integrate with the actual app, it's giving the error.

**Comment by JonasLaux** [comment]
Hey, 
unfortunately i can't reproduce your issue, because if i kick out React from my Podfile, it doesn't find any dependencies (also after linking).
This is how it looks:

`
project 'RNExampleApp.xcodeproj'
platform :ios, '10.0'

target 'RNExampleApp' do
  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
end
`

Maybe, because in our Plugin, there is still a React reference in the podspec.
Just for testing, could you 
1. go into you node_modules/anyline-ocr-react-native-module/ios and in the AnylineReact.podspec 
    remove s.dependency React
2. go to your ios folder and rm -R pods
3. pod install

**Comment by raghavendramogeraya** [comment]
Hello Jonas,
Tried removing  s.dependency React, rm -R pods and pod install again. But it throws error as below:
```
In file included from /Volumes/Development/reactnative/project1/node_modules/anyline-ocr-react-native-module/ios/AnylineSDKPlugin.m:1:
/Volumes/Development/reactnative/project1/node_modules/anyline-ocr-react-native-module/ios/AnylineSDKPlugin.h:3:9: fatal error: 'RCTBridgeModule.h' file not found
#import "RCTBridgeModule.h"
       ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
Also, recovered your podfile as previous. Then it throws error: 
```
In file included from /Volumes/Development/reactnative/project1/node_modules/anyline-ocr-react-native-module/ios/AnylineSDKPlugin.m:1:
In file included from /Volumes/Development/reactnative/project1/node_modules/anyline-ocr-react-native-module/ios/AnylineSDKPlugin.h:3:
/Volumes/Development/reactnative/project1/node_modules/react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

We are using 'yarn' for dependency management and not npm.

**Comment by JonasLaux** [comment]
Hey,
ah yeah, i think i see the problem. I will work on a fix and upload it to our next release branch today. Could you then please check it out with 

` yarn add  https://github.com/Anyline/anyline-ocr-react-native-module#release/6.0 `
I will tell you here, when it's ready

**Comment by JonasLaux** [comment]
`yarn add anyline-ocr-react-native-module@alpha`

Now, several problems can occur (unfortunately it is from the React-Native Version).

Not found config.h
- https://github.com/facebook/react-native/issues/14382#issuecomment-422755411
- `cd node_modules/react-native/third-party/glog-0.3.4/ && ../../scripts/ios-configure-glog.sh`
- if the error occur, that it doesn’t find the folder, the log-0.3.X Version can differ, please check
- if there is no third-party folder at all, try to build (and fail) the project in Xcode, after that, it should be there

libfishhook.a - Websocket
- https://github.com/facebook/react-native/issues/19569#issuecomment-422691829
- just reAdd the Link Binary

RCTDefines.h not found (very tough error, could only solve it with the other cocoapods version)
- https://github.com/facebook/react-native/issues/12265#issuecomment-380763893
- install cocoapods 1.4.0

RCTPackagerClient not found
- https://github.com/facebook/react-native/issues/17799#issuecomment-361891519
- add the subspecs to your podfile and after that, delete your pod folder and do pod install again


```
target 'RNExampleApp' do
pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'DevSupport',
   'RCTNetwork',
]
pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
end
```

**Comment by bvanleeuwen1995** [comment]
For anyone who is getting a duplicate symbol error after running the steps as described here above bij Jonas please add the following code to your Podfile to remove the React package after installation:

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end`
