### ISSUE TITLE
Android dependency conflicts with ExpoKit 32

### ISSUE THREAD

**Issue by ltankey** [Anyline/anyline-ocr-react-native-module#65]
**Anyline React-Native Plugin version:** 

`"anyline-ocr-react-native-module": "^9.0.0"`
`"expo": "^32.0.0"`
`"expokit": "32.0.7"`
`"react": "16.5.0"`
`"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"`

**I'm submitting a ...**  
[ ] bug report
[ ] feature request
[x] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**

Attempting to build, or perform an installation task, results in many errors such as:
```
node_modules/anyline-ocr-react-native-module/android/build.gradle:64: Error: This support library should not use a different version (26) than the compileSdkVersion (27) [GradleCompatible]
      implementation 'com.android.support:appcompat-v7:26.1.0'
```

Adding
```
+  implementation("com.google.android.gms:play-services-vision:17.0.2")
+  implementation("com.google.firebase:firebase-iid:17.0.3")
+  implementation("com.google.android.gms:play-services-stats:16.0.1")
+  implementation("com.google.android.gms:play-services-vision-common:17.0.2")
+  implementation("com.google.android.gms:play-services-clearcut:16.0.0")
+  implementation("com.google.android.gms:play-services-flags:16.0.1")
+  implementation("com.google.android.gms:play-services-phenotype:16.0.0")
+  implementation("com.google.firebase:firebase-iid-interop:16.0.1")
+  implementation("com.google.android.gms:play-services-basement:16.1.0")
+  implementation("com.android.support:recyclerview-v7:27.1.0")
```

to my `app/build.gradle` resolves this, but then creates further errors at the library level:

```
node_modules/anyline-ocr-react-native-module/android/build.gradle:68: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 26.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:design:26.1.0 [GradleCompatible]
      implementation 'com.android.support:design:26.1.0'
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Expected behavior:**

**Steps to reproduce:**

1. start with new `expo init` on SDK 32
2. add library, run `react-native link`
3. ensure manual linking instructions have been followed
4. attempt `./gradlew build` (or `installDevKernalDebug`)

**Other information:**

Seemingly caused by the fact the library targets sdk 26 and the expo project targets sdk 27.
To resolve this I need to update the library itself to target 27 instead of 26. Is this the intended approach to resolving these kinds of issues? It means I would have to maintain a fork that targeted that, but perhaps I'm missing something obvious.

**Comment by JonasLaux** [comment]
Hey,
thanks for submitting. No, you're not missing anything, we just don't focusing on Expo that much. On our next release we will bump those versions to fit the requirements (targetsdk on 27).

**Comment by ltankey** [comment]
Ok thanks. I wasn't sure if it was a normal challenge reconciling RN-linked libraries with the base project and its SDK target, and whether or not there was a best-practice for keeping the two aligned. Funnily enough, one of the SDK warnings offered a bandaid fix (which seems to be generally frowned upon on the internet) of disabling the `abordOnError` linting rule, which is something Expo projects start with themselves.

But that's probably less preferable to just updating the target platform.

**Comment by JonasLaux** [comment]
Definitely less preferable^^
But thanks for pointing it out!
