### ISSUE TITLE
Error while generating signed APK

### ISSUE THREAD

**Issue by tvhimanshu** [Anyline/anyline-ocr-react-native-module#67]
**Anyline React-Native Plugin version:** 
 "anyline-ocr-react-native-module": "^10.0.0"

**I'm submitting a ...**  
bug report

**Occurring on ...**  
Android

**Current behavior:**
```
What went wrong:
Could not resolve all files for configuration ':anyline-ocr-react-native-module:releaseCompileClasspath'.
> Could not download anylinesdk.aar (io.anyline:anylinesdk:10): Skipped due to earlier error
```

**Steps to reproduce:**
Generating signed APK

**Comment by JonasLaux** [comment]
Hey,
which buildTypes do you have in your build.gradle? Seems to correlate with Android Studio 3, which version of AS are you using? Are you using the example app or your own?
Seems related to [this](https://stackoverflow.com/questions/46949622/android-studio-3-0-unable-to-resolve-dependency-for-appdexoptions-compileclas), did you try the changes already?

**Comment by JonasLaux** [comment]
Hey @tvhimanshu 
did it work out? Do you need more informations?
