### ISSUE TITLE
Passport scan (MRZ) returns misspelled first name

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#7]
I'm scanning my passport and half the time it says my name is Mark, and half the time Hark :) As far as I understand, MRZ incorporates a checksum, so it shouldn't be possible for the wrong value to be returned.

**Comment by danielalbertini** [comment]
Hi,

thx for your Feedback. We are already working on an improved classification for MRZ.

As of the checksum, yes we check for that and return in the delegate/listener if all the checksums are valid. So you can decide on your own if you want to throw away the result. That's useful if you are just interested in a particular part of the MRZ and don't want to have longer scanning times or there are actually a significant amount of passports with errors in the MRZ.

If you are only interested in scans with a valid checksum you can easily modify our wrappers to throw away this results and continue scanning.

**Comment by mvayngrib** [comment]
@danielalbertini that makes sense, and I see that that can be easily edited in on the native side. Still, it would be good to have that config option on the javascript side, to not waste time sending large images over the slow react native bridge

**Comment by JonasLaux** [comment]
This is fixed by release 3.23 and the introduction of the StrictMode.

**Comment by mvayngrib** [comment]
@JonasLaux awesome, thanks!

**Comment by brunoschuermans** [comment]
Hello
I'm trying to use the anyline react-native module but impossible to launch neither an example nor a project from scratch. Would you have a running example? thx

**Comment by JonasLaux** [comment]
Hi, please use a new issue for that with a normal error description. We have an example in this repo, without any informations i can't help you
