### ISSUE TITLE
RN v 0.60.4 Android build fails

### ISSUE THREAD

**Issue by llanginger** [Anyline/anyline-ocr-react-native-module#71]
**Anyline React-Native Plugin version:** 

12.1.0

**I'm submitting a ...**  
[x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x ] Android
[ ] iOS

**Current behavior:**

Android fails to build on react native version 0.60.4 

**Expected behavior:**

Following Anyline install instructions would produce a successful Android build

**Steps to reproduce:**

Create a fresh `react-native init` project, follow the Anyline install instructions and attempt to run `react-native run-android`

**Related code:**

```
> Configure project :anyline-ocr-react-native-module
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.anyline:anylinesdk:12.1.
     Searched in the following locations:
       - file:/Users/leolanginger/.m2/repository/io/anyline/anylinesdk/12.1/anylinesdk-12.1.pom
       - file:/Users/leolanginger/.m2/repository/io/anyline/anylinesdk/12.1/anylinesdk-12.1.aar
       - file:/Users/leolanginger/Desktop/Projects/motionFolder/aws/appProjectFolder/motion_customer_mobile_app_rn_v2/node_modules/react-native/android/io/anyline/anylinesdk/12.1/anylinesdk-12.1.pom
       - file:/Users/leolanginger/Desktop/Projects/motionFolder/aws/appProjectFolder/motion_customer_mobile_app_rn_v2/node_modules/react-native/android/io/anyline/anylinesdk/12.1/anylinesdk-12.1.aar
       - file:/Users/leolanginger/Desktop/Projects/motionFolder/aws/appProjectFolder/motion_customer_mobile_app_rn_v2/node_modules/jsc-android/dist/io/anyline/anylinesdk/12.1/anylinesdk-12.1.pom
       - file:/Users/leolanginger/Desktop/Projects/motionFolder/aws/appProjectFolder/motion_customer_mobile_app_rn_v2/node_modules/jsc-android/dist/io/anyline/anylinesdk/12.1/anylinesdk-12.1.aar
       - https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/12.1/anylinesdk-12.1.pom
       - https://dl.google.com/dl/android/maven2/io/anyline/anylinesdk/12.1/anylinesdk-12.1.aar
       - https://jcenter.bintray.com/io/anyline/anylinesdk/12.1/anylinesdk-12.1.pom
       - https://jcenter.bintray.com/io/anyline/anylinesdk/12.1/anylinesdk-12.1.aar
     Required by:
         project :app > project :anyline-ocr-react-native-module
```

**Other information:**

**Comment by llanginger** [comment]
Hey Jonas, thanks for the quick response!

I was really hoping I'd made such a dumb mistake but unfortunately it doesn't look like it.

I've got a minimal repo for you to take a look at, here;

https://github.com/llanginger/anyline060

That said, the steps to reproduce (the exact steps I follow in that repo) are:

1: `react-native init`
2: `yarn add anyline-ocr-react-native-module`
3: edit android/build.gradle && .../MainApplication.java according to Anyline docs
4: `react-native run-android`

**Comment by JonasLaux** [comment]
Could you put [This maven object](https://github.com/llanginger/anyline060/blob/master/android/build.gradle#L14) into below [allprojects repository object](https://github.com/llanginger/anyline060/blob/master/android/build.gradle#L37)?

**Comment by llanginger** [comment]
No change in error, I'm afraid. Tried with the maven object in both locations as well as just under the allprojects section

**Comment by llanginger** [comment]
Deleted incorrect response.

That appears to have worked, thanks - looks like it was indeed error on my end. Thanks so much again for your fast responses!

**Comment by JonasLaux** [comment]
No problem! Glad i could help :)
