### ISSUE TITLE
Unable to compile, cannot find symbol ScanViewPluginComposite 

### ISSUE THREAD

**Issue by JBuijgers** [Anyline/anyline-ocr-react-native-module#74]
**Anyline React-Native Plugin version:** 
13.0.0

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[x] Android
[ ] iOS

**Current behavior:**
After running 'react-native run-android', the following error is produced:
> Task :anyline-ocr-react-native-module:compileDebugJavaWithJavac FAILED
[..]/node_modules/anyline-ocr-react-native-module/android/src/main/java/com/anyline/reactnative/Anyline4Activity.java:52: error: cannot find symbol
import io.anyline.view.ScanViewPluginComposite;
                      ^
  symbol:   class ScanViewPluginComposite
  location: package io.anyline.view

**Expected behavior:**
Being able to compile.

**Steps to reproduce:**
Update package.json > "anyline-ocr-react-native-module": "~13.0.0"
rm -rf node_modules
yarn install
react-native run-android

**Related code:**
N/A

**Other information:**
There is no usage of ScanViewPluginComposite (and a few others) in the Anyline4Activity.java file, after commenting this line, compiling and all other functionality works.

**Comment by JonasLaux** [comment]
Hey,
thanks for pointing out, we released a hotfix for it!
https://github.com/Anyline/anyline-ocr-react-native-module/releases/tag/v13.1.0
