### ISSUE TITLE
Error Scanning Full Document: Unrecognized Format

### ISSUE THREAD

**Issue by roberto-rodriguez** [Anyline/anyline-ocr-react-native-module#78]
I just installed the sample app, 
then select DOCUMENT SCANNER option and try to scan a real check picture,

then I get this:
Error Scanning Full Document: Unrecognized Format

What does this mean?
Please help.

**Comment by gseebacher** [comment]
Hi Roberto,

the sample app reads formats appx. A4. 
please try to scan this format.
thanks,
cheers
Gerhard
