### ISSUE TITLE
iOS example is not using lastest Anyline version

### ISSUE THREAD

**Issue by sorgnardt** [Anyline/anyline-ocr-react-native-module#79]
**Anyline React-Native Plugin version:** 

**I'm submitting a ...**  
[ ] bug report
[ x] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[ x] iOS

**Current behavior:**

iOS example is SDK 15.1
**Expected behavior:**

iOS should use lastest iOS 16.x
**Steps to reproduce:**

**Related code:**

```
			inputPaths = (
				"${PODS_ROOT}/Target Support Files/Pods-RNExampleApp/Pods-RNExampleApp-resources.sh",
				"${PODS_ROOT}/Anyline/AnylineSDK_iOS_15.1/Framework/AnylineResources.bundle",
			);
```

**Other information:**

**Comment by JonasLaux** [comment]
Hey,
The example app does not refer to an Anyline version. This is just the latest Pod config in the project. You can just install the latest anyline-react-native plugin via NPM and then go into your example app 
root/ios and fire up the Cocoapod update commands.

`pod repo update`
`rm -rf Pods Podfile.lock && pod update --verbose`

This will install the newest Anyline SDK.
