### ISSUE TITLE
Using the document scanner UI

### ISSUE THREAD

**Issue by JBuijgers** [Anyline/anyline-ocr-react-native-module#85]
**Anyline React-Native Plugin version:** 
19

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ x ] Android
[ ] iOS

**Current behavior:**
In my config, I've got documentScannerUI: true, but no document scanner UI is showing up. Are the example config files in this repo correct? As per https://documentation.anyline.com/toc/demos/index.html#document-demo, are these values possible as well? Or are we limited to just setting documentScannerUI to true. If it is possible, where would I put these config values?

**Expected behavior:**
The document scanner UI should show up.

**Steps to reproduce:**
Upgrade to v19 of this package
Copy config from example/RNExampleApp/config/DocumentConfigUI.js
No document scanner UI is showing up

**Related code:**
anylineConfig equals contents of example/RNExampleApp/config/DocumentConfigUI.js
```
await AnylineOCR.setupPromise(anylineConfig, "scan")
```

**Other information:**

**Comment by JonasLaux** [comment]
@gseebacher can you have a look at this?

**Comment by gseebacher** [comment]
hi JBuijgers,
the Document Scanner UI is not (yet) available for React-Native.
