### ISSUE TITLE
[feature request] custom hint/instructions on scan screen

### ISSUE THREAD

**Issue by mvayngrib** [Anyline/anyline-ocr-react-native-module#9]
I was playing around with scanning different driver licenses, and I didn't know I needed to position the barcode in the middle of the cutout, rather than position the whole license in the middle of the cutout. The scanning performance is a million times better in the first case. I would like to give a hint/instruction to the user to that effect, e.g. "If a barcodes is present, center it in the scanning area for best results". I checked the config json documentation but can't find an option for this. Thanks!

**Comment by danielalbertini** [comment]
Yes sounds like a good feature.

I would propose a simple label, which can be laid out similar to the segment for different meter modes.

**Comment by mvayngrib** [comment]
@danielalbertini that sounds great

**Comment by JonasLaux** [comment]
19540f489afebb862aac3df793bf91eddd7d2842
