### ISSUE TITLE
[Android] Native crashes on scan + APK size increased

### ISSUE THREAD

**Issue by krizzu** [Anyline/anyline-ocr-react-native-module#90]
Hello,

I'm implementing Anyline into my project with latest version of RN. I have a problem to get it running due to native issues. Also, the APK size after adding `anyline` has almost doubled (from ~70MB, went up to ~120MB).

**Anyline React-Native Plugin version:** 
v23

**I'm submitting a ...**  
[X] bug report
[X] feature request
[ ] general question

**Occurring on ...**  
[X] Android

### Native crashes

In my project (RN 0.63.2), in order to get Android build and install, I had to select different native libs, due to multiple instances:

```
    packagingOptions {
        pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
        pickFirst 'lib/x86/libgnustl_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
```

On Android, upon calling Anyline with `setupPromise`, scanning activity is opened, but after few seconds I get this crash (and apps is ANR)

```

      ‼️  Uncaught Exception: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/X.staging-2/lib/arm64/libanylineCore.so"...
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/X-2/lib/arm64/libanylineCore.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at io.anyline.plugin.AbstractScanPlugin.<clinit>(SourceFile:3)
        at io.anyline.plugin.barcode.BarcodeScanViewPlugin.<init>(SourceFile:3)
        at io.anyline.view.JsonParser.parseViewPlugin(SourceFile:191)
        at io.anyline.view.JsonParser.init(SourceFile:52)
        at io.anyline.view.ScanView.initComposite(SourceFile:3)
        at io.anyline.view.ScanView.init(SourceFile:15)
        at io.anyline.view.ScanView.setScanConfig(SourceFile:4)
    	at com.anyline.reactnative.Anyline4Activity.initAnyline(Anyline4Activity.java:1
```

Also, running your local android example throws error when selecting one of the scans:

```
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/com.anyline.example.reactnative-1/lib/arm64/libanylineCore.so"...
```

**Expected behavior:**

Library working, no much impact on APK size.

**Other information:**

I'm testing this on device (abi `arm64-v8a`) where crash is happening:

```
Processor	: AArch64 Processor rev 2 (aarch64)
processor	: 0
model name	: AArch64 Processor rev 2 (aarch64)
BogoMIPS	: 26.00
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2
```

**However**, my other device (high-end), same arch, but different revision works just fine:

```
Processor	: AArch64 Processor rev 12 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0x7
CPU part	: 0x803
CPU revision	: 12
```

### APK Size

After integrating `Anyline`, the APK size is huge (visible even in Example app). Analyzing APK seems like there's a lot of MB coming from this library (screenshot from Example app):

![Screenshot 2020-09-10 at 15 55 24](https://user-images.githubusercontent.com/6444719/92740527-18757080-f37e-11ea-8f33-ba91f84897f5.png)
 
Question is, is there a way to get slimmer version of Anyline, if I only use `VIN` and `PDF_417` Plugins?

Thanks!

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
