### ISSUE TITLE
Document scanner toast

### ISSUE THREAD

**Issue by JBuijgers** [Anyline/anyline-ocr-react-native-module#91]
**Anyline React-Native Plugin version:** 23

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ x ] Android
[ ] iOS

**Current behavior:**
After a document is scanned, a toast is displayed with the path of the scanned image.

**Expected behavior:**
Do not show toast at all.

**Steps to reproduce:**
N/a

**Related code:**
N/a

**Other information:**
This was previously fixed in https://github.com/Anyline/anyline-ocr-react-native-module/pull/56 not sure why this feature got removed, but either restore it or remove the toast all together. React Native provides plenty of libraries to show a toast, no need for AnyLine to force this.

**Comment by gseebacher** [comment]
Hi Jost, we will fix this issue in the next release (release 24; planned release date Sept. 23)

**Comment by JBuijgers** [comment]
Great to hear, thanks for the reply!
