### ISSUE TITLE
Deleting unrelated modules to reduce app size

### ISSUE THREAD

**Issue by yahm23** [Anyline/anyline-ocr-react-native-module#95]
**Anyline React-Native Plugin version:** 
24.2.0

**I'm submitting a ...**   
[ ] bug report
[ ] feature request
[x] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behaviour:**
We're trying to reduce our application size. And currently only use the Energy meter scanning from the package.

After we used Analyze APK to see what were the main offenders in app size, Anyline had 17.6% of the storage with 24.7MB total (see image below). We only use the energy meter reading from the package, and the other modules (module_id etc.) take up an excess of 10% of our app's total size. My question is if every modules are needed for Anyline to work? If not, can we delete them? And would this be as simple finding them in the node modules and doing so?

<img width="676" alt="Screenshot 2020-10-29 at 16 44 21" src="https://user-images.githubusercontent.com/55092073/97604975-002ce400-1a06-11eb-9b26-e61d560f4a1d.png">

**Expected behaviour:**
Being able to reduce app total size by deleting non-used modules.

**Comment by benlondon** [comment]
This is possible now following [this guide](https://documentation.anyline.com/toc/platforms/android/reduce_sdk_size.html).

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
