### ISSUE TITLE
Anyline doesn't support scan Credit card?

### ISSUE THREAD

**Issue by minhchienwikipedia** [Anyline/anyline-ocr-react-native-module#97]
**I'm submitting a ...**  
[ ] bug report
[x ] feature request
[x ] general question

**Occurring on ...**  
[ x] Android
[ x] iOS

**Current behavior:**
I can't find the config for the scan credit card, I had installed your app on the Play store but I can't find where to scan it too. So I wonder Anyline doesn't support it?

**Comment by daniLPT** [comment]
Hi, we don't support it yet but are working on it internally. Unfortunately I can't say when it will be ready for a public release. Best, Daniel

**Comment by minhchienwikipedia** [comment]
@daniLPT Thanks for the reply, I hope it will be released soon!
